"""
Report generator for exporting analysis results as PDF.
Uses fpdf2 for PDF generation.
"""

import io
import json
from datetime import datetime
from typing import Dict, Any


def generate_contract_analysis_pdf(analysis: Dict[str, Any],
                                    filename: str = "") -> bytes:
    """Generate a PDF report for a contract analysis."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "Contract Analysis Report", ln=True, align="C")
    pdf.ln(5)

    # Meta info
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    if filename:
        pdf.cell(0, 6, f"Document: {filename}", ln=True)
    pdf.cell(0, 6, f"Jurisdiction: {analysis.get('jurisdiction', 'N/A')}", ln=True)
    pdf.cell(0, 6, f"Contract Type: {analysis.get('contract_type', 'N/A')}", ln=True)
    pdf.ln(5)

    # Risk Score
    risk_score = analysis.get("overall_risk_score", 0)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"Overall Risk Score: {risk_score}/10", ln=True)

    # Risk level indicator
    if risk_score <= 3:
        pdf.set_text_color(34, 197, 94)
        level = "LOW RISK"
    elif risk_score <= 6:
        pdf.set_text_color(234, 179, 8)
        level = "MEDIUM RISK"
    else:
        pdf.set_text_color(239, 68, 68)
        level = "HIGH RISK"
    pdf.cell(0, 8, level, ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    # Summary
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Executive Summary", ln=True)
    pdf.set_font("Helvetica", "", 10)
    summary = analysis.get("summary", "No summary available.")
    pdf.multi_cell(0, 6, _safe_text(summary))
    pdf.ln(5)

    # Clause Analysis
    clauses = analysis.get("clauses", [])
    if isinstance(clauses, str):
        try:
            clauses = json.loads(clauses)
        except Exception:
            clauses = []

    if clauses:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, f"Clause Analysis ({len(clauses)} clauses found)", ln=True)
        pdf.ln(3)

        for clause in clauses:
            pdf.set_font("Helvetica", "B", 10)
            c_type = clause.get("clause_type", "Unknown")
            c_score = clause.get("risk_score", 0)
            c_level = clause.get("risk_level", "low")

            # Color code
            if c_level == "high":
                pdf.set_text_color(239, 68, 68)
            elif c_level == "medium":
                pdf.set_text_color(180, 140, 0)
            else:
                pdf.set_text_color(34, 150, 80)

            pdf.cell(0, 6, f"{c_type} (Risk: {c_score}/10 - {c_level.upper()})", ln=True)
            pdf.set_text_color(0, 0, 0)

            pdf.set_font("Helvetica", "", 9)
            explanation = clause.get("explanation", "")
            if explanation:
                pdf.multi_cell(0, 5, _safe_text(f"  {explanation}"))

            suggestion = clause.get("suggestion", "")
            if suggestion:
                pdf.set_font("Helvetica", "I", 9)
                pdf.multi_cell(0, 5, _safe_text(f"  Suggestion: {suggestion}"))
            pdf.ln(3)

    # Recommendations
    recommendations = analysis.get("recommendations", [])
    if isinstance(recommendations, str):
        try:
            recommendations = json.loads(recommendations)
        except Exception:
            recommendations = []

    if recommendations:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Recommendations", ln=True)
        pdf.set_font("Helvetica", "", 10)
        for i, rec in enumerate(recommendations, 1):
            pdf.multi_cell(0, 6, _safe_text(f"{i}. {rec}"))
        pdf.ln(5)

    # Disclaimer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 4, _safe_text(
        "DISCLAIMER: This is an AI-generated legal analysis and does NOT constitute legal advice. "
        "Consult a qualified lawyer for your specific situation. "
        "Generated by AI Legal Consultation Platform."
    ))

    return pdf.output()


def generate_summary_pdf(summary: Dict[str, Any],
                          filename: str = "") -> bytes:
    """Generate a PDF report for a document summary."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "Document Summary Report", ln=True, align="C")
    pdf.ln(5)

    # Meta
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    if filename:
        pdf.cell(0, 6, f"Document: {filename}", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    # Executive Summary
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Executive Summary", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, _safe_text(summary.get("executive_summary", "No summary available.")))
    pdf.ln(5)

    # Key Points
    key_points = summary.get("key_points", [])
    if isinstance(key_points, str):
        try:
            key_points = json.loads(key_points)
        except Exception:
            key_points = []

    if key_points:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Key Points", ln=True)
        pdf.set_font("Helvetica", "", 10)
        for point in key_points:
            pdf.multi_cell(0, 6, _safe_text(f"  * {point}"))
        pdf.ln(5)

    # Action Items
    action_items = summary.get("action_items", [])
    if isinstance(action_items, str):
        try:
            action_items = json.loads(action_items)
        except Exception:
            action_items = []

    if action_items:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Action Items", ln=True)
        pdf.set_font("Helvetica", "", 10)
        for item in action_items:
            if isinstance(item, dict):
                action = item.get("action", str(item))
                priority = item.get("priority", "")
                deadline = item.get("deadline", "")
                line = f"  * {action}"
                if priority:
                    line += f" [{priority.upper()}]"
                if deadline:
                    line += f" (Due: {deadline})"
                pdf.multi_cell(0, 6, _safe_text(line))
            else:
                pdf.multi_cell(0, 6, _safe_text(f"  * {item}"))
        pdf.ln(5)

    # Disclaimer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 4, _safe_text(
        "DISCLAIMER: This is an AI-generated summary and may not capture all details. "
        "Always refer to the original document for complete information. "
        "Generated by AI Legal Consultation Platform."
    ))

    return pdf.output()


def _safe_text(text: str) -> str:
    """Make text safe for PDF output (replace unsupported characters)."""
    if not text:
        return ""
    # Replace common Unicode characters with ASCII equivalents
    replacements = {
        "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "--",
        "\u2026": "...",
        "\u2022": "*",
        "\u00a7": "S.",  # Section symbol
        "\u00b6": "P.",  # Paragraph symbol
        "\u2713": "[OK]",
        "\u2717": "[X]",
        "\u2605": "*",
        "\u26a0": "[!]",
        "\U0001f534": "[HIGH]",
        "\U0001f7e1": "[MED]",
        "\U0001f7e2": "[LOW]",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    # Remove any remaining non-latin1 characters
    text = text.encode("latin-1", errors="replace").decode("latin-1")
    return text
